name: Check PR for required checkbox

on:
  release:
    types: [opened, synchronize, edited]

jobs:
  check_pull_request:
    name: Check PR for required checkbox
    runs-on: linux
    container:
      image: docker-hub.battle.net/wm/docker-base-ubuntu:22.04
      options: --user root
    steps:    
      - name: Checkout repository
Â        uses: actions/checkout@v2
      - name: Check pull request description
        env:
          BODY: ${{ github.event.pull_request.body }}
        uses: ./pr-checkbox.yml
